version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/github.com/ShunyaNagashige/stringer-interface
    ports:
      #APIサーバ用のポート
      - ${API_PORT}:8080